// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: service_qwetu_backend.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QwetuBackendGrpcService_CreateUser_FullMethodName = "/pb.QwetuBackendGrpcService/CreateUser"
	QwetuBackendGrpcService_LoginUser_FullMethodName  = "/pb.QwetuBackendGrpcService/LoginUser"
)

// QwetuBackendGrpcServiceClient is the client API for QwetuBackendGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QwetuBackendGrpcServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type qwetuBackendGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQwetuBackendGrpcServiceClient(cc grpc.ClientConnInterface) QwetuBackendGrpcServiceClient {
	return &qwetuBackendGrpcServiceClient{cc}
}

func (c *qwetuBackendGrpcServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, QwetuBackendGrpcService_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qwetuBackendGrpcServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, QwetuBackendGrpcService_LoginUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QwetuBackendGrpcServiceServer is the server API for QwetuBackendGrpcService service.
// All implementations must embed UnimplementedQwetuBackendGrpcServiceServer
// for forward compatibility
type QwetuBackendGrpcServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedQwetuBackendGrpcServiceServer()
}

// UnimplementedQwetuBackendGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQwetuBackendGrpcServiceServer struct {
}

func (UnimplementedQwetuBackendGrpcServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedQwetuBackendGrpcServiceServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedQwetuBackendGrpcServiceServer) mustEmbedUnimplementedQwetuBackendGrpcServiceServer() {
}

// UnsafeQwetuBackendGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QwetuBackendGrpcServiceServer will
// result in compilation errors.
type UnsafeQwetuBackendGrpcServiceServer interface {
	mustEmbedUnimplementedQwetuBackendGrpcServiceServer()
}

func RegisterQwetuBackendGrpcServiceServer(s grpc.ServiceRegistrar, srv QwetuBackendGrpcServiceServer) {
	s.RegisterService(&QwetuBackendGrpcService_ServiceDesc, srv)
}

func _QwetuBackendGrpcService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QwetuBackendGrpcServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QwetuBackendGrpcService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QwetuBackendGrpcServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QwetuBackendGrpcService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QwetuBackendGrpcServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QwetuBackendGrpcService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QwetuBackendGrpcServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QwetuBackendGrpcService_ServiceDesc is the grpc.ServiceDesc for QwetuBackendGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QwetuBackendGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.QwetuBackendGrpcService",
	HandlerType: (*QwetuBackendGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _QwetuBackendGrpcService_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _QwetuBackendGrpcService_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_qwetu_backend.proto",
}
