// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qwetu_petro/backend/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	db "github.com/qwetu_petro/backend/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ApprovePaymentRequest mocks base method.
func (m *MockStore) ApprovePaymentRequest(arg0 context.Context, arg1 db.ApprovePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePaymentRequest", arg0, arg1)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApprovePaymentRequest indicates an expected call of ApprovePaymentRequest.
func (mr *MockStoreMockRecorder) ApprovePaymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePaymentRequest", reflect.TypeOf((*MockStore)(nil).ApprovePaymentRequest), arg0, arg1)
}

// ApprovePaymentRequestWithAudit mocks base method.
func (m *MockStore) ApprovePaymentRequestWithAudit(arg0 context.Context, arg1 int32, arg2 db.ApprovePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePaymentRequestWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApprovePaymentRequestWithAudit indicates an expected call of ApprovePaymentRequestWithAudit.
func (mr *MockStoreMockRecorder) ApprovePaymentRequestWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePaymentRequestWithAudit", reflect.TypeOf((*MockStore)(nil).ApprovePaymentRequestWithAudit), arg0, arg1, arg2)
}

// ApprovePettyCash mocks base method.
func (m *MockStore) ApprovePettyCash(arg0 context.Context, arg1 db.ApprovePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePettyCash", arg0, arg1)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApprovePettyCash indicates an expected call of ApprovePettyCash.
func (mr *MockStoreMockRecorder) ApprovePettyCash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePettyCash", reflect.TypeOf((*MockStore)(nil).ApprovePettyCash), arg0, arg1)
}

// ApprovePettyCashWithAudit mocks base method.
func (m *MockStore) ApprovePettyCashWithAudit(arg0 context.Context, arg1 int32, arg2 db.ApprovePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePettyCashWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApprovePettyCashWithAudit indicates an expected call of ApprovePettyCashWithAudit.
func (mr *MockStoreMockRecorder) ApprovePettyCashWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePettyCashWithAudit", reflect.TypeOf((*MockStore)(nil).ApprovePettyCashWithAudit), arg0, arg1, arg2)
}

// CreateBankDetails mocks base method.
func (m *MockStore) CreateBankDetails(arg0 context.Context, arg1 db.CreateBankDetailsParams) (db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankDetails", arg0, arg1)
	ret0, _ := ret[0].(db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankDetails indicates an expected call of CreateBankDetails.
func (mr *MockStoreMockRecorder) CreateBankDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankDetails", reflect.TypeOf((*MockStore)(nil).CreateBankDetails), arg0, arg1)
}

// CreateCar mocks base method.
func (m *MockStore) CreateCar(arg0 context.Context, arg1 db.CreateCarParams) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCar", arg0, arg1)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCar indicates an expected call of CreateCar.
func (mr *MockStoreMockRecorder) CreateCar(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCar", reflect.TypeOf((*MockStore)(nil).CreateCar), arg0, arg1)
}

// CreateCompany mocks base method.
func (m *MockStore) CreateCompany(arg0 context.Context, arg1 db.CreateCompanyParams) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompany", arg0, arg1)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompany indicates an expected call of CreateCompany.
func (mr *MockStoreMockRecorder) CreateCompany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompany", reflect.TypeOf((*MockStore)(nil).CreateCompany), arg0, arg1)
}

// CreateFuelConsumption mocks base method.
func (m *MockStore) CreateFuelConsumption(arg0 context.Context, arg1 db.CreateFuelConsumptionParams) (db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFuelConsumption", arg0, arg1)
	ret0, _ := ret[0].(db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFuelConsumption indicates an expected call of CreateFuelConsumption.
func (mr *MockStoreMockRecorder) CreateFuelConsumption(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFuelConsumption", reflect.TypeOf((*MockStore)(nil).CreateFuelConsumption), arg0, arg1)
}

// CreateInvoice mocks base method.
func (m *MockStore) CreateInvoice(arg0 context.Context, arg1 db.CreateInvoiceParams) (db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", arg0, arg1)
	ret0, _ := ret[0].(db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockStoreMockRecorder) CreateInvoice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockStore)(nil).CreateInvoice), arg0, arg1)
}

// CreateInvoiceItem mocks base method.
func (m *MockStore) CreateInvoiceItem(arg0 context.Context, arg1 db.CreateInvoiceItemParams) (db.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoiceItem", arg0, arg1)
	ret0, _ := ret[0].(db.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoiceItem indicates an expected call of CreateInvoiceItem.
func (mr *MockStoreMockRecorder) CreateInvoiceItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoiceItem", reflect.TypeOf((*MockStore)(nil).CreateInvoiceItem), arg0, arg1)
}

// CreateInvoiceTxn mocks base method.
func (m *MockStore) CreateInvoiceTxn(arg0 context.Context, arg1 int32, arg2 db.CreateInvoiceParams, arg3 []db.CreateInvoiceItemParams) (db.InvoiceTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoiceTxn", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(db.InvoiceTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoiceTxn indicates an expected call of CreateInvoiceTxn.
func (mr *MockStoreMockRecorder) CreateInvoiceTxn(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoiceTxn", reflect.TypeOf((*MockStore)(nil).CreateInvoiceTxn), arg0, arg1, arg2, arg3)
}

// CreatePaymentRequest mocks base method.
func (m *MockStore) CreatePaymentRequest(arg0 context.Context, arg1 db.CreatePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentRequest", arg0, arg1)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentRequest indicates an expected call of CreatePaymentRequest.
func (mr *MockStoreMockRecorder) CreatePaymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentRequest", reflect.TypeOf((*MockStore)(nil).CreatePaymentRequest), arg0, arg1)
}

// CreatePaymentRequestWithAudit mocks base method.
func (m *MockStore) CreatePaymentRequestWithAudit(arg0 context.Context, arg1 int32, arg2 db.CreatePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentRequestWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentRequestWithAudit indicates an expected call of CreatePaymentRequestWithAudit.
func (mr *MockStoreMockRecorder) CreatePaymentRequestWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentRequestWithAudit", reflect.TypeOf((*MockStore)(nil).CreatePaymentRequestWithAudit), arg0, arg1, arg2)
}

// CreatePettyCash mocks base method.
func (m *MockStore) CreatePettyCash(arg0 context.Context, arg1 db.CreatePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePettyCash", arg0, arg1)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePettyCash indicates an expected call of CreatePettyCash.
func (mr *MockStoreMockRecorder) CreatePettyCash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePettyCash", reflect.TypeOf((*MockStore)(nil).CreatePettyCash), arg0, arg1)
}

// CreatePettyCashWithAudit mocks base method.
func (m *MockStore) CreatePettyCashWithAudit(arg0 context.Context, arg1 int32, arg2 db.CreatePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePettyCashWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePettyCashWithAudit indicates an expected call of CreatePettyCashWithAudit.
func (mr *MockStoreMockRecorder) CreatePettyCashWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePettyCashWithAudit", reflect.TypeOf((*MockStore)(nil).CreatePettyCashWithAudit), arg0, arg1, arg2)
}

// CreatePurchaseOrder mocks base method.
func (m *MockStore) CreatePurchaseOrder(arg0 context.Context, arg1 db.CreatePurchaseOrderParams) (db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchaseOrder", arg0, arg1)
	ret0, _ := ret[0].(db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchaseOrder indicates an expected call of CreatePurchaseOrder.
func (mr *MockStoreMockRecorder) CreatePurchaseOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchaseOrder", reflect.TypeOf((*MockStore)(nil).CreatePurchaseOrder), arg0, arg1)
}

// CreatePurchaseOrderItem mocks base method.
func (m *MockStore) CreatePurchaseOrderItem(arg0 context.Context, arg1 db.CreatePurchaseOrderItemParams) (db.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchaseOrderItem", arg0, arg1)
	ret0, _ := ret[0].(db.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchaseOrderItem indicates an expected call of CreatePurchaseOrderItem.
func (mr *MockStoreMockRecorder) CreatePurchaseOrderItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchaseOrderItem", reflect.TypeOf((*MockStore)(nil).CreatePurchaseOrderItem), arg0, arg1)
}

// CreatePurchaseOrderTxn mocks base method.
func (m *MockStore) CreatePurchaseOrderTxn(arg0 context.Context, arg1 db.CreatePurchaseOrderTxParams, arg2 int32) (db.PurchaseOrderTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchaseOrderTxn", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.PurchaseOrderTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchaseOrderTxn indicates an expected call of CreatePurchaseOrderTxn.
func (mr *MockStoreMockRecorder) CreatePurchaseOrderTxn(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchaseOrderTxn", reflect.TypeOf((*MockStore)(nil).CreatePurchaseOrderTxn), arg0, arg1, arg2)
}

// CreateQuotation mocks base method.
func (m *MockStore) CreateQuotation(arg0 context.Context, arg1 db.CreateQuotationParams) (db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuotation", arg0, arg1)
	ret0, _ := ret[0].(db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuotation indicates an expected call of CreateQuotation.
func (mr *MockStoreMockRecorder) CreateQuotation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuotation", reflect.TypeOf((*MockStore)(nil).CreateQuotation), arg0, arg1)
}

// CreateQuotationItem mocks base method.
func (m *MockStore) CreateQuotationItem(arg0 context.Context, arg1 db.CreateQuotationItemParams) (db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuotationItem", arg0, arg1)
	ret0, _ := ret[0].(db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuotationItem indicates an expected call of CreateQuotationItem.
func (mr *MockStoreMockRecorder) CreateQuotationItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuotationItem", reflect.TypeOf((*MockStore)(nil).CreateQuotationItem), arg0, arg1)
}

// CreateQuotationTxn mocks base method.
func (m *MockStore) CreateQuotationTxn(arg0 context.Context, arg1 int32, arg2 db.CreateQuotationTxParams) (db.QuotationTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuotationTxn", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.QuotationTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuotationTxn indicates an expected call of CreateQuotationTxn.
func (mr *MockStoreMockRecorder) CreateQuotationTxn(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuotationTxn", reflect.TypeOf((*MockStore)(nil).CreateQuotationTxn), arg0, arg1, arg2)
}

// CreateRole mocks base method.
func (m *MockStore) CreateRole(arg0 context.Context, arg1 db.CreateRoleParams) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockStoreMockRecorder) CreateRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockStore)(nil).CreateRole), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateSignatory mocks base method.
func (m *MockStore) CreateSignatory(arg0 context.Context, arg1 db.CreateSignatoryParams) (db.Signatory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSignatory", arg0, arg1)
	ret0, _ := ret[0].(db.Signatory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSignatory indicates an expected call of CreateSignatory.
func (mr *MockStoreMockRecorder) CreateSignatory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSignatory", reflect.TypeOf((*MockStore)(nil).CreateSignatory), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserRoles mocks base method.
func (m *MockStore) CreateUserRoles(arg0 context.Context, arg1 db.CreateUserRolesParams) (db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserRoles", arg0, arg1)
	ret0, _ := ret[0].(db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserRoles indicates an expected call of CreateUserRoles.
func (mr *MockStoreMockRecorder) CreateUserRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserRoles", reflect.TypeOf((*MockStore)(nil).CreateUserRoles), arg0, arg1)
}

// DeleteCompanyByName mocks base method.
func (m *MockStore) DeleteCompanyByName(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompanyByName", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompanyByName indicates an expected call of DeleteCompanyByName.
func (mr *MockStoreMockRecorder) DeleteCompanyByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompanyByName", reflect.TypeOf((*MockStore)(nil).DeleteCompanyByName), arg0, arg1)
}

// DeletePaymentRequest mocks base method.
func (m *MockStore) DeletePaymentRequest(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePaymentRequest indicates an expected call of DeletePaymentRequest.
func (mr *MockStoreMockRecorder) DeletePaymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentRequest", reflect.TypeOf((*MockStore)(nil).DeletePaymentRequest), arg0, arg1)
}

// DeletePaymentRequestWithAudit mocks base method.
func (m *MockStore) DeletePaymentRequestWithAudit(arg0 context.Context, arg1, arg2 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentRequestWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePaymentRequestWithAudit indicates an expected call of DeletePaymentRequestWithAudit.
func (mr *MockStoreMockRecorder) DeletePaymentRequestWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentRequestWithAudit", reflect.TypeOf((*MockStore)(nil).DeletePaymentRequestWithAudit), arg0, arg1, arg2)
}

// DeletePettyCash mocks base method.
func (m *MockStore) DeletePettyCash(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePettyCash", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePettyCash indicates an expected call of DeletePettyCash.
func (mr *MockStoreMockRecorder) DeletePettyCash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePettyCash", reflect.TypeOf((*MockStore)(nil).DeletePettyCash), arg0, arg1)
}

// DeletePettyCashWithAudit mocks base method.
func (m *MockStore) DeletePettyCashWithAudit(arg0 context.Context, arg1, arg2 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePettyCashWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePettyCashWithAudit indicates an expected call of DeletePettyCashWithAudit.
func (mr *MockStoreMockRecorder) DeletePettyCashWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePettyCashWithAudit", reflect.TypeOf((*MockStore)(nil).DeletePettyCashWithAudit), arg0, arg1, arg2)
}

// DeleteRole mocks base method.
func (m *MockStore) DeleteRole(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockStoreMockRecorder) DeleteRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockStore)(nil).DeleteRole), arg0, arg1)
}

// DeleteSignatoryByName mocks base method.
func (m *MockStore) DeleteSignatoryByName(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSignatoryByName", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSignatoryByName indicates an expected call of DeleteSignatoryByName.
func (mr *MockStoreMockRecorder) DeleteSignatoryByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSignatoryByName", reflect.TypeOf((*MockStore)(nil).DeleteSignatoryByName), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// DeleteUserRoles mocks base method.
func (m *MockStore) DeleteUserRoles(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRoles", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRoles indicates an expected call of DeleteUserRoles.
func (mr *MockStoreMockRecorder) DeleteUserRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRoles", reflect.TypeOf((*MockStore)(nil).DeleteUserRoles), arg0, arg1)
}

// DeleteUserRolesByRole mocks base method.
func (m *MockStore) DeleteUserRolesByRole(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRolesByRole", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRolesByRole indicates an expected call of DeleteUserRolesByRole.
func (mr *MockStoreMockRecorder) DeleteUserRolesByRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRolesByRole", reflect.TypeOf((*MockStore)(nil).DeleteUserRolesByRole), arg0, arg1)
}

// GetBankDetailsByAccountNumber mocks base method.
func (m *MockStore) GetBankDetailsByAccountNumber(arg0 context.Context, arg1 string) (db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankDetailsByAccountNumber", arg0, arg1)
	ret0, _ := ret[0].(db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankDetailsByAccountNumber indicates an expected call of GetBankDetailsByAccountNumber.
func (mr *MockStoreMockRecorder) GetBankDetailsByAccountNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankDetailsByAccountNumber", reflect.TypeOf((*MockStore)(nil).GetBankDetailsByAccountNumber), arg0, arg1)
}

// GetBankInfoByID mocks base method.
func (m *MockStore) GetBankInfoByID(arg0 context.Context, arg1 int32) (db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankInfoByID", arg0, arg1)
	ret0, _ := ret[0].(db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankInfoByID indicates an expected call of GetBankInfoByID.
func (mr *MockStoreMockRecorder) GetBankInfoByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankInfoByID", reflect.TypeOf((*MockStore)(nil).GetBankInfoByID), arg0, arg1)
}

// GetCars mocks base method.
func (m *MockStore) GetCars(arg0 context.Context, arg1 db.GetCarsParams) ([]db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCars", arg0, arg1)
	ret0, _ := ret[0].([]db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCars indicates an expected call of GetCars.
func (mr *MockStoreMockRecorder) GetCars(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCars", reflect.TypeOf((*MockStore)(nil).GetCars), arg0, arg1)
}

// GetCompanyByID mocks base method.
func (m *MockStore) GetCompanyByID(arg0 context.Context, arg1 int64) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByID", arg0, arg1)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyByID indicates an expected call of GetCompanyByID.
func (mr *MockStoreMockRecorder) GetCompanyByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByID", reflect.TypeOf((*MockStore)(nil).GetCompanyByID), arg0, arg1)
}

// GetConsumptionByCar mocks base method.
func (m *MockStore) GetConsumptionByCar(arg0 context.Context, arg1 int32) ([]db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumptionByCar", arg0, arg1)
	ret0, _ := ret[0].([]db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumptionByCar indicates an expected call of GetConsumptionByCar.
func (mr *MockStoreMockRecorder) GetConsumptionByCar(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumptionByCar", reflect.TypeOf((*MockStore)(nil).GetConsumptionByCar), arg0, arg1)
}

// GetConsumptionByCarAndDateRange mocks base method.
func (m *MockStore) GetConsumptionByCarAndDateRange(arg0 context.Context, arg1 db.GetConsumptionByCarAndDateRangeParams) ([]db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumptionByCarAndDateRange", arg0, arg1)
	ret0, _ := ret[0].([]db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumptionByCarAndDateRange indicates an expected call of GetConsumptionByCarAndDateRange.
func (mr *MockStoreMockRecorder) GetConsumptionByCarAndDateRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumptionByCarAndDateRange", reflect.TypeOf((*MockStore)(nil).GetConsumptionByCarAndDateRange), arg0, arg1)
}

// GetConsumptions mocks base method.
func (m *MockStore) GetConsumptions(arg0 context.Context, arg1 db.GetConsumptionsParams) ([]db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumptions", arg0, arg1)
	ret0, _ := ret[0].([]db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumptions indicates an expected call of GetConsumptions.
func (mr *MockStoreMockRecorder) GetConsumptions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumptions", reflect.TypeOf((*MockStore)(nil).GetConsumptions), arg0, arg1)
}

// GetInvoiceById mocks base method.
func (m *MockStore) GetInvoiceById(arg0 context.Context, arg1 int32) (db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceById", arg0, arg1)
	ret0, _ := ret[0].(db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceById indicates an expected call of GetInvoiceById.
func (mr *MockStoreMockRecorder) GetInvoiceById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceById", reflect.TypeOf((*MockStore)(nil).GetInvoiceById), arg0, arg1)
}

// GetInvoiceItemsByInvoiceID mocks base method.
func (m *MockStore) GetInvoiceItemsByInvoiceID(arg0 context.Context, arg1 int32) ([]db.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceItemsByInvoiceID", arg0, arg1)
	ret0, _ := ret[0].([]db.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceItemsByInvoiceID indicates an expected call of GetInvoiceItemsByInvoiceID.
func (mr *MockStoreMockRecorder) GetInvoiceItemsByInvoiceID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceItemsByInvoiceID", reflect.TypeOf((*MockStore)(nil).GetInvoiceItemsByInvoiceID), arg0, arg1)
}

// GetInvoicesByPurchaseOrderNumber mocks base method.
func (m *MockStore) GetInvoicesByPurchaseOrderNumber(arg0 context.Context, arg1 string) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicesByPurchaseOrderNumber", arg0, arg1)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoicesByPurchaseOrderNumber indicates an expected call of GetInvoicesByPurchaseOrderNumber.
func (mr *MockStoreMockRecorder) GetInvoicesByPurchaseOrderNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicesByPurchaseOrderNumber", reflect.TypeOf((*MockStore)(nil).GetInvoicesByPurchaseOrderNumber), arg0, arg1)
}

// GetPaymentRequest mocks base method.
func (m *MockStore) GetPaymentRequest(arg0 context.Context, arg1 int32) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentRequest", arg0, arg1)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentRequest indicates an expected call of GetPaymentRequest.
func (mr *MockStoreMockRecorder) GetPaymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentRequest", reflect.TypeOf((*MockStore)(nil).GetPaymentRequest), arg0, arg1)
}

// GetPettyCash mocks base method.
func (m *MockStore) GetPettyCash(arg0 context.Context, arg1 int32) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPettyCash", arg0, arg1)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPettyCash indicates an expected call of GetPettyCash.
func (mr *MockStoreMockRecorder) GetPettyCash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPettyCash", reflect.TypeOf((*MockStore)(nil).GetPettyCash), arg0, arg1)
}

// GetPurchaseOrder mocks base method.
func (m *MockStore) GetPurchaseOrder(arg0 context.Context, arg1 int32) (db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseOrder", arg0, arg1)
	ret0, _ := ret[0].(db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseOrder indicates an expected call of GetPurchaseOrder.
func (mr *MockStoreMockRecorder) GetPurchaseOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseOrder", reflect.TypeOf((*MockStore)(nil).GetPurchaseOrder), arg0, arg1)
}

// GetPurchaseOrderItemsByPurchaseOrderID mocks base method.
func (m *MockStore) GetPurchaseOrderItemsByPurchaseOrderID(arg0 context.Context, arg1 *int32) ([]db.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseOrderItemsByPurchaseOrderID", arg0, arg1)
	ret0, _ := ret[0].([]db.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseOrderItemsByPurchaseOrderID indicates an expected call of GetPurchaseOrderItemsByPurchaseOrderID.
func (mr *MockStoreMockRecorder) GetPurchaseOrderItemsByPurchaseOrderID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseOrderItemsByPurchaseOrderID", reflect.TypeOf((*MockStore)(nil).GetPurchaseOrderItemsByPurchaseOrderID), arg0, arg1)
}

// GetQuotationByID mocks base method.
func (m *MockStore) GetQuotationByID(arg0 context.Context, arg1 int32) (db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotationByID", arg0, arg1)
	ret0, _ := ret[0].(db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotationByID indicates an expected call of GetQuotationByID.
func (mr *MockStoreMockRecorder) GetQuotationByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotationByID", reflect.TypeOf((*MockStore)(nil).GetQuotationByID), arg0, arg1)
}

// GetQuotationItemsByQuotationID mocks base method.
func (m *MockStore) GetQuotationItemsByQuotationID(arg0 context.Context, arg1 int32) ([]db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotationItemsByQuotationID", arg0, arg1)
	ret0, _ := ret[0].([]db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotationItemsByQuotationID indicates an expected call of GetQuotationItemsByQuotationID.
func (mr *MockStoreMockRecorder) GetQuotationItemsByQuotationID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotationItemsByQuotationID", reflect.TypeOf((*MockStore)(nil).GetQuotationItemsByQuotationID), arg0, arg1)
}

// GetRole mocks base method.
func (m *MockStore) GetRole(arg0 context.Context, arg1 int64) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockStoreMockRecorder) GetRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockStore)(nil).GetRole), arg0, arg1)
}

// GetSessionByID mocks base method.
func (m *MockStore) GetSessionByID(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockStoreMockRecorder) GetSessionByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockStore)(nil).GetSessionByID), arg0, arg1)
}

// GetSignatoryById mocks base method.
func (m *MockStore) GetSignatoryById(arg0 context.Context, arg1 int64) (db.Signatory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatoryById", arg0, arg1)
	ret0, _ := ret[0].(db.Signatory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatoryById indicates an expected call of GetSignatoryById.
func (mr *MockStoreMockRecorder) GetSignatoryById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatoryById", reflect.TypeOf((*MockStore)(nil).GetSignatoryById), arg0, arg1)
}

// GetUserByUserNameOrEmail mocks base method.
func (m *MockStore) GetUserByUserNameOrEmail(arg0 context.Context, arg1 db.GetUserByUserNameOrEmailParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserNameOrEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserNameOrEmail indicates an expected call of GetUserByUserNameOrEmail.
func (mr *MockStoreMockRecorder) GetUserByUserNameOrEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserNameOrEmail", reflect.TypeOf((*MockStore)(nil).GetUserByUserNameOrEmail), arg0, arg1)
}

// GetUserRole mocks base method.
func (m *MockStore) GetUserRole(arg0 context.Context, arg1 db.GetUserRoleParams) (db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", arg0, arg1)
	ret0, _ := ret[0].(db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockStoreMockRecorder) GetUserRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockStore)(nil).GetUserRole), arg0, arg1)
}

// GetUserRoles mocks base method.
func (m *MockStore) GetUserRoles(arg0 context.Context, arg1 int64) ([]db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", arg0, arg1)
	ret0, _ := ret[0].([]db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockStoreMockRecorder) GetUserRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockStore)(nil).GetUserRoles), arg0, arg1)
}

// GetUsers mocks base method.
func (m *MockStore) GetUsers(arg0 context.Context, arg1 db.GetUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", arg0, arg1)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockStoreMockRecorder) GetUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockStore)(nil).GetUsers), arg0, arg1)
}

// ListBankDetailsByBankName mocks base method.
func (m *MockStore) ListBankDetailsByBankName(arg0 context.Context, arg1 string) ([]db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankDetailsByBankName", arg0, arg1)
	ret0, _ := ret[0].([]db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBankDetailsByBankName indicates an expected call of ListBankDetailsByBankName.
func (mr *MockStoreMockRecorder) ListBankDetailsByBankName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankDetailsByBankName", reflect.TypeOf((*MockStore)(nil).ListBankDetailsByBankName), arg0, arg1)
}

// ListBanks mocks base method.
func (m *MockStore) ListBanks(arg0 context.Context) ([]db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBanks", arg0)
	ret0, _ := ret[0].([]db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBanks indicates an expected call of ListBanks.
func (mr *MockStoreMockRecorder) ListBanks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBanks", reflect.TypeOf((*MockStore)(nil).ListBanks), arg0)
}

// ListCompanies mocks base method.
func (m *MockStore) ListCompanies(arg0 context.Context, arg1 db.ListCompaniesParams) ([]db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompanies", arg0, arg1)
	ret0, _ := ret[0].([]db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompanies indicates an expected call of ListCompanies.
func (mr *MockStoreMockRecorder) ListCompanies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompanies", reflect.TypeOf((*MockStore)(nil).ListCompanies), arg0, arg1)
}

// ListEmployeePaymentRequests mocks base method.
func (m *MockStore) ListEmployeePaymentRequests(arg0 context.Context, arg1 db.ListEmployeePaymentRequestsParams) ([]db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeePaymentRequests", arg0, arg1)
	ret0, _ := ret[0].([]db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeePaymentRequests indicates an expected call of ListEmployeePaymentRequests.
func (mr *MockStoreMockRecorder) ListEmployeePaymentRequests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeePaymentRequests", reflect.TypeOf((*MockStore)(nil).ListEmployeePaymentRequests), arg0, arg1)
}

// ListEmployeePettyCash mocks base method.
func (m *MockStore) ListEmployeePettyCash(arg0 context.Context, arg1 db.ListEmployeePettyCashParams) ([]db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeePettyCash", arg0, arg1)
	ret0, _ := ret[0].([]db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeePettyCash indicates an expected call of ListEmployeePettyCash.
func (mr *MockStoreMockRecorder) ListEmployeePettyCash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeePettyCash", reflect.TypeOf((*MockStore)(nil).ListEmployeePettyCash), arg0, arg1)
}

// ListInvoiceItemsByInvoiceID mocks base method.
func (m *MockStore) ListInvoiceItemsByInvoiceID(arg0 context.Context, arg1 int32) ([]db.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvoiceItemsByInvoiceID", arg0, arg1)
	ret0, _ := ret[0].([]db.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvoiceItemsByInvoiceID indicates an expected call of ListInvoiceItemsByInvoiceID.
func (mr *MockStoreMockRecorder) ListInvoiceItemsByInvoiceID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvoiceItemsByInvoiceID", reflect.TypeOf((*MockStore)(nil).ListInvoiceItemsByInvoiceID), arg0, arg1)
}

// ListInvoices mocks base method.
func (m *MockStore) ListInvoices(arg0 context.Context, arg1 db.ListInvoicesParams) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvoices", arg0, arg1)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvoices indicates an expected call of ListInvoices.
func (mr *MockStoreMockRecorder) ListInvoices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvoices", reflect.TypeOf((*MockStore)(nil).ListInvoices), arg0, arg1)
}

// ListPaymentRequests mocks base method.
func (m *MockStore) ListPaymentRequests(arg0 context.Context, arg1 db.ListPaymentRequestsParams) ([]db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaymentRequests", arg0, arg1)
	ret0, _ := ret[0].([]db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaymentRequests indicates an expected call of ListPaymentRequests.
func (mr *MockStoreMockRecorder) ListPaymentRequests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentRequests", reflect.TypeOf((*MockStore)(nil).ListPaymentRequests), arg0, arg1)
}

// ListPettyCash mocks base method.
func (m *MockStore) ListPettyCash(arg0 context.Context, arg1 db.ListPettyCashParams) ([]db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPettyCash", arg0, arg1)
	ret0, _ := ret[0].([]db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPettyCash indicates an expected call of ListPettyCash.
func (mr *MockStoreMockRecorder) ListPettyCash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPettyCash", reflect.TypeOf((*MockStore)(nil).ListPettyCash), arg0, arg1)
}

// ListPurchaseOrderItemsByPurchaseOrderID mocks base method.
func (m *MockStore) ListPurchaseOrderItemsByPurchaseOrderID(arg0 context.Context, arg1 *int32) ([]db.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurchaseOrderItemsByPurchaseOrderID", arg0, arg1)
	ret0, _ := ret[0].([]db.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurchaseOrderItemsByPurchaseOrderID indicates an expected call of ListPurchaseOrderItemsByPurchaseOrderID.
func (mr *MockStoreMockRecorder) ListPurchaseOrderItemsByPurchaseOrderID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurchaseOrderItemsByPurchaseOrderID", reflect.TypeOf((*MockStore)(nil).ListPurchaseOrderItemsByPurchaseOrderID), arg0, arg1)
}

// ListPurchaseOrders mocks base method.
func (m *MockStore) ListPurchaseOrders(arg0 context.Context, arg1 db.ListPurchaseOrdersParams) ([]db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurchaseOrders", arg0, arg1)
	ret0, _ := ret[0].([]db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurchaseOrders indicates an expected call of ListPurchaseOrders.
func (mr *MockStoreMockRecorder) ListPurchaseOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurchaseOrders", reflect.TypeOf((*MockStore)(nil).ListPurchaseOrders), arg0, arg1)
}

// ListQuotationItemsByQuotationID mocks base method.
func (m *MockStore) ListQuotationItemsByQuotationID(arg0 context.Context, arg1 int32) ([]db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuotationItemsByQuotationID", arg0, arg1)
	ret0, _ := ret[0].([]db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuotationItemsByQuotationID indicates an expected call of ListQuotationItemsByQuotationID.
func (mr *MockStoreMockRecorder) ListQuotationItemsByQuotationID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuotationItemsByQuotationID", reflect.TypeOf((*MockStore)(nil).ListQuotationItemsByQuotationID), arg0, arg1)
}

// ListQuotations mocks base method.
func (m *MockStore) ListQuotations(arg0 context.Context, arg1 db.ListQuotationsParams) ([]db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuotations", arg0, arg1)
	ret0, _ := ret[0].([]db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuotations indicates an expected call of ListQuotations.
func (mr *MockStoreMockRecorder) ListQuotations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuotations", reflect.TypeOf((*MockStore)(nil).ListQuotations), arg0, arg1)
}

// ListRoles mocks base method.
func (m *MockStore) ListRoles(arg0 context.Context, arg1 db.ListRolesParams) ([]db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", arg0, arg1)
	ret0, _ := ret[0].([]db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockStoreMockRecorder) ListRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockStore)(nil).ListRoles), arg0, arg1)
}

// ListSignatories mocks base method.
func (m *MockStore) ListSignatories(arg0 context.Context, arg1 db.ListSignatoriesParams) ([]db.Signatory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSignatories", arg0, arg1)
	ret0, _ := ret[0].([]db.Signatory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSignatories indicates an expected call of ListSignatories.
func (mr *MockStoreMockRecorder) ListSignatories(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSignatories", reflect.TypeOf((*MockStore)(nil).ListSignatories), arg0, arg1)
}

// ListSiteInvoices mocks base method.
func (m *MockStore) ListSiteInvoices(arg0 context.Context, arg1 db.ListSiteInvoicesParams) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSiteInvoices", arg0, arg1)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSiteInvoices indicates an expected call of ListSiteInvoices.
func (mr *MockStoreMockRecorder) ListSiteInvoices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSiteInvoices", reflect.TypeOf((*MockStore)(nil).ListSiteInvoices), arg0, arg1)
}

// ListUserCompanyInvoices mocks base method.
func (m *MockStore) ListUserCompanyInvoices(arg0 context.Context, arg1 db.ListUserCompanyInvoicesParams) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserCompanyInvoices", arg0, arg1)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserCompanyInvoices indicates an expected call of ListUserCompanyInvoices.
func (mr *MockStoreMockRecorder) ListUserCompanyInvoices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserCompanyInvoices", reflect.TypeOf((*MockStore)(nil).ListUserCompanyInvoices), arg0, arg1)
}

// UpdatePaymentRequest mocks base method.
func (m *MockStore) UpdatePaymentRequest(arg0 context.Context, arg1 db.UpdatePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentRequest", arg0, arg1)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePaymentRequest indicates an expected call of UpdatePaymentRequest.
func (mr *MockStoreMockRecorder) UpdatePaymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentRequest", reflect.TypeOf((*MockStore)(nil).UpdatePaymentRequest), arg0, arg1)
}

// UpdatePaymentRequestWithAudit mocks base method.
func (m *MockStore) UpdatePaymentRequestWithAudit(arg0 context.Context, arg1 int32, arg2 db.UpdatePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentRequestWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePaymentRequestWithAudit indicates an expected call of UpdatePaymentRequestWithAudit.
func (mr *MockStoreMockRecorder) UpdatePaymentRequestWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentRequestWithAudit", reflect.TypeOf((*MockStore)(nil).UpdatePaymentRequestWithAudit), arg0, arg1, arg2)
}

// UpdatePettyCash mocks base method.
func (m *MockStore) UpdatePettyCash(arg0 context.Context, arg1 db.UpdatePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePettyCash", arg0, arg1)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePettyCash indicates an expected call of UpdatePettyCash.
func (mr *MockStoreMockRecorder) UpdatePettyCash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePettyCash", reflect.TypeOf((*MockStore)(nil).UpdatePettyCash), arg0, arg1)
}

// UpdatePettyCashWithAudit mocks base method.
func (m *MockStore) UpdatePettyCashWithAudit(arg0 context.Context, arg1 int32, arg2 db.UpdatePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePettyCashWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePettyCashWithAudit indicates an expected call of UpdatePettyCashWithAudit.
func (mr *MockStoreMockRecorder) UpdatePettyCashWithAudit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePettyCashWithAudit", reflect.TypeOf((*MockStore)(nil).UpdatePettyCashWithAudit), arg0, arg1, arg2)
}

// UpdateQuotation mocks base method.
func (m *MockStore) UpdateQuotation(arg0 context.Context, arg1 db.UpdateQuotationParams) (db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotation", arg0, arg1)
	ret0, _ := ret[0].(db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuotation indicates an expected call of UpdateQuotation.
func (mr *MockStoreMockRecorder) UpdateQuotation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotation", reflect.TypeOf((*MockStore)(nil).UpdateQuotation), arg0, arg1)
}

// UpdateQuotationItem mocks base method.
func (m *MockStore) UpdateQuotationItem(arg0 context.Context, arg1 db.UpdateQuotationItemParams) (db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotationItem", arg0, arg1)
	ret0, _ := ret[0].(db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuotationItem indicates an expected call of UpdateQuotationItem.
func (mr *MockStoreMockRecorder) UpdateQuotationItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotationItem", reflect.TypeOf((*MockStore)(nil).UpdateQuotationItem), arg0, arg1)
}

// UpdateQuotationTxn mocks base method.
func (m *MockStore) UpdateQuotationTxn(arg0 context.Context, arg1 int32, arg2 db.UpdateQuotationTxParams) (db.UpdateQuotationTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotationTxn", arg0, arg1, arg2)
	ret0, _ := ret[0].(db.UpdateQuotationTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuotationTxn indicates an expected call of UpdateQuotationTxn.
func (mr *MockStoreMockRecorder) UpdateQuotationTxn(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotationTxn", reflect.TypeOf((*MockStore)(nil).UpdateQuotationTxn), arg0, arg1, arg2)
}

// UpdateRole mocks base method.
func (m *MockStore) UpdateRole(arg0 context.Context, arg1 db.UpdateRoleParams) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockStoreMockRecorder) UpdateRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockStore)(nil).UpdateRole), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateUserRoles mocks base method.
func (m *MockStore) UpdateUserRoles(arg0 context.Context, arg1 db.UpdateUserRolesParams) (db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoles", arg0, arg1)
	ret0, _ := ret[0].(db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRoles indicates an expected call of UpdateUserRoles.
func (mr *MockStoreMockRecorder) UpdateUserRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoles", reflect.TypeOf((*MockStore)(nil).UpdateUserRoles), arg0, arg1)
}
